title: Taurus Consulting
description: >
    Taurus offers the creative solutions for completing your capital needs and
    attaining your financing.
baseurl: ""
url: "https://www.tauruscapital.net" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
gems:
    - jekyll-feed
exclude:
    - Gemfile
    - Gemfile.lock
